version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: course
    networks:
      - ntSearch
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    image: course
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=course
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=course
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ntSearch

networks:
  ntSearch:
    driver: bridge
